### ISSUE TITLE
App crashes when using a mutableStateLisOf<LocalDate> instead of a ListOf<LocalDate> 

### ISSUE THREAD

**Issue by David8aO** [boguszpawlowski/ComposeCalendar#102]
Works fine at first on current month (YearMonth.now()) but scrolling to further months will cause the app to crash.
With the next error code: 

 java.lang.IllegalStateException: Check failed.
at androidx.compose.ui.focus.FocusInvalidationManager$invalidateNodes$1.invoke(FocusInvalidationManager.kt:187)
at androidx.compose.ui.focus.FocusInvalidationManager$invalidateNodes$1.invoke(FocusInvalidationManager.kt:60)

**Comment by boguszpawlowski** [comment]
Hi @David8aO Can you provide a code snippet or sample project that would help reproduce the issue? Not sure how to proceed with informarion provided.

**Comment by David8aO** [comment]
Update
Turns out what was causing the crash was a .then() modifier, which i was using to make clickable only the dates in a initial list.
Deleting the modifier solved the problem.
