### ISSUE TITLE
Feature Request: Add Swipe Event Callback for SelectableWeekCalendar and SelectableCalendar

### ISSUE THREAD

**Issue by anvukelic** [boguszpawlowski/ComposeCalendar#104]
**Description:**
Currently, the **SelectableWeekCalendar** and **SelectableCalendar** components can detect swipe gestures. However, we propose adding a new feature: a callback function for swipe events.

**Feature Details:**
The callback will notify developers whenever a user performs a swipe gesture on the calendar UI. It will provide information about the swipe direction (left, right, or next/previous month/week) or even better, a list of currently visible dates.

**Use Cases:**
The swipe event callback will enable developers to:

- Implement custom actions when users swipe on specific dates or areas of the calendar.
- Create intuitive gesture-based navigation between different calendar views.
- Enhance the overall user experience with smooth and responsive UI interactions.

Please let me know what you think of it

**Comment by anvukelic** [comment]
I created PR for this and also for the other ticket where I asked if should we maybe keep the weekdays not scrollable since they are not changing.

https://github.com/boguszpawlowski/ComposeCalendar/pull/106

Let me know WDYT

**Comment by boguszpawlowski** [comment]
@anvukelic  In the current state of #106 we could achieve exactly the same thing using:
```
 LaunchedEffect(Unit) {
    snapshotFlow {
      calendarState.monthState.currentMonth
    }.onEach { currentMonth ->
      Timber.tag("new month").d(currentMonth.toString())
    }.launchIn(this)
  }
```
It wouldn't require any work on the library side, and is pretty straightforward to implement on the client side. Does it fulfil your Use-case?

**Comment by boguszpawlowski** [comment]
Closing per: https://github.com/boguszpawlowski/ComposeCalendar/issues/104#issuecomment-1694717786
