### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by Raynafs** [boguszpawlowski/ComposeCalendar#108]
Is there a way I can reduce the tile size that holds the month and the year? also maybe change the size of the cards as well?

**Comment by boguszpawlowski** [comment]
Hi @Raynafs. The components supplied by the library are only for feature showcase. If you want to style the component, it is encouraged to supply your own, via the `monthHeader` property of the calendar. You can check how to do it in `CustomComponentSample`.

**Comment by boguszpawlowski** [comment]
@Raynafs Hope it answers your question. If not, feel free to reopen this issue.

**Comment by Raynafs** [comment]
Yes sure. I did figure it out. Thank you.
