### ISSUE TITLE
Project does not build when this library is included

### ISSUE THREAD

**Issue by edlingem** [boguszpawlowski/ComposeCalendar#110]
Gradle build error, when this library is included. (KMM Project)
After a gradle clean, the app runs again - but if I try to run it again, it shows this error.

![Bildschirmfoto 2023-10-08 um 16 44 10](https://github.com/boguszpawlowski/ComposeCalendar/assets/98261425/e046d114-ead4-4bd3-86cf-3eb2c19299b4)

If any further information is needed, please let me know 😄

**Comment by SyedAliSalman** [comment]
> Gradle build error, when this library is included. (KMM Project) After a gradle clean, the app runs again - but if I try to run it again, it shows this error.
> 
> ![Bildschirmfoto 2023-10-08 um 16 44 10](https://user-images.githubusercontent.com/98261425/273455340-e046d114-ead4-4bd3-86cf-3eb2c19299b4.png)
> 
> If any further information is needed, please let me know 😄

@edlingem did you found a solution or work around? I am facing similar issue.

**Comment by boguszpawlowski** [comment]
Hi, could you create a sample project that would recreate the issue? That would help with fixing the problem. Thanks!
