### ISSUE TITLE
Custom dayContent, monthHeader and weekHeader

### ISSUE THREAD

**Issue by ChavezJA** [boguszpawlowski/ComposeCalendar#43]
I was modifying this 3 things to make it fit my requirements but when I do scroll or click on the arrows to the prev/next month the view doesn't updates with it

https://user-images.githubusercontent.com/88408422/155017789-af1601d6-0063-45e7-a2ba-54c352de6d20.mp4

**Comment by boguszpawlowski** [comment]
@ChavezJA Thanks for submitting the issue. Can you please provide the source code for your month header / create a sample project which reproduces the behaviour. Also, please add info about used library version. Thank you!

**Comment by boguszpawlowski** [comment]
@ChavezJA Since you didn't provide the necessary data, I will close this issue. Feel free to reopen it with additional information.
