### ISSUE TITLE
Adjust month name to respect Locale

### ISSUE THREAD

**Issue by LeoColman** [boguszpawlowski/ComposeCalendar#48]
https://github.com/boguszpawlowski/ComposeCalendar/blob/afff02d8cb1c53c0ae6b89b020e0b8ed72f03a7e/library/src/main/java/io/github/boguszpawlowski/composecalendar/header/DefaultMonthHeader.kt#L47

In line 47 of `DefaultMonthHeader`we use the enum name as the month name. This will always default to English!

In Java 8 (used by Android and currently used by this lib) we have the method `getDisplayName`, which I believe is more suitable to the situation, as it will respect users' locale.

https://docs.oracle.com/javase/8/docs/api/java/time/Month.html#getDisplayName-java.time.format.TextStyle-java.util.Locale-

My UseCase is that my app is in Brazilian-Portuguese, and I'm unable to customize the month display name without reimplementing the `DefaultMonthHeader`.

**Comment by boguszpawlowski** [comment]
@LeoColman Thanks for the contribution, issues should be fixed in 0.4.1-SNAPSHOT. Can you confirm on your end?

**Comment by LeoColman** [comment]
Yes!
I tested with 0.4.1-SNAPSHOT and it fixed it to the default locale.
I also took a look at PR #49 and it seems exactly what I would implement if I would do it myself, so the PR seems perfect too 🗡️ 

Thanks for the quick work on this one, @boguszpawlowski !

**Comment by boguszpawlowski** [comment]
Great! I have triggered a 4.0.1 release, should be available in Maven Central in about half an hour
