### ISSUE TITLE
Allow content in `DefaultDay` to be customizable

### ISSUE THREAD

**Issue by LeoColman** [boguszpawlowski/ComposeCalendar#54]
# Context
The current implementation for DefaultDay includes what will be inside the card in its totality.
The changes you can apply from outside are limited, as they're mainly for the colors.

# Use cases/ the problem
![image](https://user-images.githubusercontent.com/1577251/160219894-492a7776-1da7-4141-afd3-3e557e656e79.png)
Given a Calendar, what I want to do is add small icons inside the Day block.

# Current workarounds
Currently, there is a way to do it, which is to implement my own `Day`. It's simple and effective.

# Improvements

Given all the facts, there is still room for improvement.

## Suggestion 1: Extract the UI part to a different function and add it as a customizable default to `DefaultDay`

```
Card(
    modifier = modifier
      .aspectRatio(1f)
      .padding(2.dp),
    elevation = if (state.isFromCurrentMonth) 4.dp else 0.dp,
    border = if (state.isCurrentDay) BorderStroke(1.dp, currentDayColor) else null,
    contentColor = if (isSelected) selectionColor else contentColorFor(
      backgroundColor = MaterialTheme.colors.surface
    )
  ) {
    Box(
      modifier = Modifier.clickable {
        onClick(date)
        selectionState.onDateSelected(date)
      },
      contentAlignment = Alignment.Center,
    ) {
      Text(text = date.dayOfMonth.toString())
    }
  }
```

This guy here can go to a separate function, supported as public api:

```
public fun DefaultDayContent(....) { }
```

which can be snuck into
```
@Composable
public fun <T : SelectionState> DefaultDay(
  state: DayState<T>,
  modifier: Modifier = Modifier,
  selectionColor: Color = MaterialTheme.colors.secondary,
  currentDayColor: Color = MaterialTheme.colors.primary,
  onClick: (LocalDate) -> Unit = {},
)
```

## Suggestion 2: Add the possibility to add icons/content below the calendar

Take a look at this great library:
https://github.com/Applandeo/Material-Calendar-View

It contains a special customization to add icons and such to the calendar

![image](https://user-images.githubusercontent.com/1577251/160220509-ebbfc0cf-c682-48c5-8485-b0b21ebdf48b.png)

We can support this here.
`BelowCalendarNumber` composable/parameter seems appropriate

**Comment by boguszpawlowski** [comment]
@LeoColman Again, big thanks for the contribution! 
The approach no2 is something I would like to avoid. The declarative style of Compose allows us to define the API using the `Slot` approach, which is IMO much better than passing view-like attributes to composable functions. 

As for the approach no1, I'm not sure if it wouldn't confuse the consumers of the library too much. Right now, you have a clear composable responsible for rendering the day content, and you don't have to wonder which part of code you have to replace with your implementation in order to customize the calendar. TBH, I'm not sure what would be the role of `DefaultDay` after the change. I'm open to a further discussion, and I'm eager to hear your opinion on this!

**Comment by LeoColman** [comment]
Ok, so what I want to do is kind of merge the two suggestions?

Let's take a look at `SelectableCalendar` [here](https://github.com/boguszpawlowski/ComposeCalendar/blob/main/library/src/main/java/io/github/boguszpawlowski/composecalendar/Calendar.kt)

```
public fun SelectableCalendar(
  modifier: Modifier = Modifier,
  firstDayOfWeek: DayOfWeek = WeekFields.of(Locale.getDefault()).firstDayOfWeek,
  today: LocalDate = LocalDate.now(),
  showAdjacentMonths: Boolean = true,
  horizontalSwipeEnabled: Boolean = true,
  calendarState: CalendarState<DynamicSelectionState> = rememberSelectableCalendarState(),
  dayContent: @Composable BoxScope.(DayState<DynamicSelectionState>) -> Unit = { DefaultDay(it) },
  monthHeader: @Composable ColumnScope.(MonthState) -> Unit = { DefaultMonthHeader(it) },
  weekHeader: @Composable BoxScope.(List<DayOfWeek>) -> Unit = { DefaultWeekHeader(it) },
  monthContainer: @Composable (content: @Composable (PaddingValues) -> Unit) -> Unit = { content ->
    Box { content(PaddingValues()) }
  },
)

```

It uses `DefaultDay` by default.

What is the effort from the user side to implement a Day that contains Icons?

Currently, I have to write the entire function:

```
@Composable
public fun <T : SelectionState> AnAlternativeDayWithARowOfIcons(
  state: DayState<T>,
  modifier: Modifier = Modifier,
  selectionColor: Color = MaterialTheme.colors.secondary,
  currentDayColor: Color = MaterialTheme.colors.primary,
  onClick: (LocalDate) -> Unit = {},
  icon: Icon
) {
  val date = state.date
  val selectionState = state.selectionState

  val isSelected = selectionState.isDateSelected(date)

  Card(
    modifier = modifier
      .aspectRatio(1f)
      .padding(2.dp),
    elevation = if (state.isFromCurrentMonth) 4.dp else 0.dp,
    border = if (state.isCurrentDay) BorderStroke(1.dp, currentDayColor) else null,
    contentColor = if (isSelected) selectionColor else contentColorFor(
      backgroundColor = MaterialTheme.colors.surface
    )
  ) {
    Box(
      modifier = Modifier.clickable {
        onClick(date)
        selectionState.onDateSelected(date)
      },
      contentAlignment = Alignment.Center,
    ) {
	  Column {
          Text(text = date.dayOfMonth.toString())
          Icon(icon)
      }
    }
  }
}
```


If we take a look at the [DefaultDay implementation](https://github.com/boguszpawlowski/ComposeCalendar/blob/main/library/src/main/java/io/github/boguszpawlowski/composecalendar/day/DefaultDay.kt), we'll see that my custom implementation is very similar to the one present in the library.

![image](https://user-images.githubusercontent.com/1577251/160489306-eae35bfe-edc2-4ef4-a842-e9fd596e26db.png)



And in the end I'll replace the lines
```kotlin
dayContent: @Composable BoxScope.(DayState<DynamicSelectionState>) -> Unit = { DefaultDay(it) },
```
with
```kotlin
dayContent: @Composable BoxScope.(DayState<DynamicSelectionState>) -> Unit = { AnAlternativeDayWithARowOfIcons(it, Icons.Home) },
```

This part of the API is flexible enough to allow me to add my custom day.

However, `DefaultDay` isn't flexible enough to be more customizable. Instead of adding the whole `AnAlternativeDayWithARowOfIcons` function, I'd rather call a slightly different version of `DefaultDay` or a public `AbstractDay` of some sort which is part of the lilbrary, instead of creating my own method that I'll have to maintain

**Comment by LeoColman** [comment]
Do you think this makes more sense now?
I think I could put some more details to what I was thinking :D

**Comment by boguszpawlowski** [comment]
@LeoColman  Do you want to provide a draft with the proposed solution? It shouldn't be too complicated, and I think it could allow as to have better understanding of the proposition.

**Comment by boguszpawlowski** [comment]
@LeoColman Do you want to provide a draft of such approach?

**Comment by LeoColman** [comment]
No, sorry. Shifted my attention elsewhere.
Let's close this for the time being
