### ISSUE TITLE
Give @LeoColman permission to edit labels

### ISSUE THREAD

**Issue by LeoColman** [boguszpawlowski/ComposeCalendar#56]
Hey @boguszpawlowski !

Could you give me permission to add labels to the issues I create? I'd love to keep the issues page beautiful and colored.

**Comment by boguszpawlowski** [comment]
TBH I'm not sure how to provide this kind of access 😄

**Comment by LeoColman** [comment]
I think in `Settings` you can add members as `Contributors`
This will give me access to close issues, change tags, and I don't remember all the information.
I'm trying to find the link for it, but failing to

**Comment by boguszpawlowski** [comment]
I'm sorry, but the only option I can see is to add you as a collaborator, and I'm not yet comfortable granting such a level of control. I hope you understand. For now, you can tell me what kind of labels would be beneficial to have, and I will happily add them.

**Comment by LeoColman** [comment]
Absolutely!

No worries, I'll get through you eventually.

I thought there was a "Contributor" option which would have less permissions than a "collaborator". Maybe that's only for organizations.

My problem is just that I can't add labels to the issues I create, and I hate to leave them unlabelled xD
