### ISSUE TITLE
Month range.

### ISSUE THREAD

**Issue by ta-shi** [boguszpawlowski/ComposeCalendar#66]
Is there a way to limit the number of months to show?

E,g. allow only from this month to the next 4 months.

**Comment by boguszpawlowski** [comment]
Hi @ta-shi! No, currently there is no functionality for it. I can see this as a viable use-case, so any contribution for this is most-welcome. As for now, you can disable clicking/selecting months out of range on your side as a workaround (you will have to implement a custom Day composable).
