### ISSUE TITLE
Crash with Compose 1.2.0-beta02 and Accompanist 0.24.9-beta

### ISSUE THREAD

**Issue by petr-stetka-spaceti** [boguszpawlowski/ComposeCalendar#72]
Hello, first thank you for great calendar library for compose, it is amazing.

Today I tried to update compose to version 1.2.0-beta02 and the application crashes, here is the log:

```
 java.lang.NoSuchMethodError: No static method HorizontalPager-Fsagccs(ILandroidx/compose/ui/Modifier;Lcom/google/accompanist/pager/PagerState;ZFLandroidx/compose/foundation/layout/PaddingValues;Landroidx/compose/ui/Alignment$Vertical;Landroidx/compose/foundation/gestures/FlingBehavior;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Lcom/google/accompanist/pager/Pager; or its super classes (declaration of 'com.google.accompanist.pager.Pager' appears in /data/app/~~79VTB2fvUggsaeHt0xzbrg==/com.app.example.debug-mwfocWD7L63rBycSVz1u7w==/base.apk!classes34.dex)
        at io.github.boguszpawlowski.composecalendar.month.MonthContentKt.MonthPager(MonthContent.kt:58)
        at io.github.boguszpawlowski.composecalendar.CalendarKt.Calendar(Calendar.kt:190)
        at io.github.boguszpawlowski.composecalendar.CalendarKt.SelectableCalendar(Calendar.kt:83)
```

Probably it is due to some changes in compose or a rather in a accompanist. Would it be possible to prepare a version for compose 1.2.0?

Petr Štětka

**Comment by boguszpawlowski** [comment]
Hi @petr-stetka-spaceti, unfortunately, I don't think it is viable to upgrade to a non-stable release of compose. Once the 1.2.0 will be released, I will migrate as soon as possible. Thank you for understanding.

**Comment by IstrajI** [comment]
Got same on 1.2.0 latest beta, as well on stable version
Turning horizontalSwipeEnabled to false helps me
