### ISSUE TITLE
Convert calendar to Persian

### ISSUE THREAD

**Issue by rezafaraji93** [boguszpawlowski/ComposeCalendar#79]
Is it possible to convert date to Persian date?

**Comment by boguszpawlowski** [comment]
@rezafaraji93 I'm not aware on how the Persian date differs from regular one, could you provide some details?

**Comment by rezafaraji93** [comment]
I mean converting date from Gregorian calendar to Solar Hijri Calender.

**Comment by boguszpawlowski** [comment]
@rezafaraji93 Thank you for your patience. Unfortunately, I don't know how I can implement such conversion with current library structure. If you have an idea, feel free to contribute.
