### ISSUE TITLE
Support minSdk version 24

### ISSUE THREAD

**Issue by jeongth9446** [boguszpawlowski/ComposeCalendar#83]
First of all thank you for open-sourcing such a great library.

My application is needed to setup in Android Nougat(SDK 24)
However, the library seems to be running from SDK 26 and above.
It seems that the date-related classes (DayOfWeek, etc.) have SDK 26 dependency.

Is it possible to support SDK 24 by modifying that?
![image](https://user-images.githubusercontent.com/52663419/199373087-8ad9eda0-93d5-4443-8353-6df18f2c6c42.png)

**Comment by jeongth9446** [comment]
When below code applied, your library work well in lower version SDK!

I think it would be good to add the code below to the readme.

android {
  defaultConfig {
    // Required ONLY if your minSdkVersion is below 21
    multiDexEnabled true
  }

  compileOptions {
    // Enable support for the new language APIs
    coreLibraryDesugaringEnabled true
    // Set compatibility to Java 8 (can be higher if desired)
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  kotlinOptions {
    // Also add this for Kotlin projects
    jvmTarget = "1.8"
  }
}

dependencies {
  coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:<latest-version>'
}

**Comment by boguszpawlowski** [comment]
Hi @jeongth9446! Sorry that it took me so long to answer this. I think adding a reference is a good idea, however, I would only add a link to an official documentation: https://developer.android.com/studio/write/java8-support. IMO, setup section would be the best place for it. If you want to submit a PR, feel free to do so.
