### ISSUE TITLE
How to track month state changes?

### ISSUE THREAD

**Issue by Foenix00001** [boguszpawlowski/ComposeCalendar#84]
I cannot see the callback to track the event when user changes the current month. Is there a way to do something with current month (for example I need to load events of current month and show them)?

**Comment by boguszpawlowski** [comment]
Hi @Foenix00001! I believe you can use `snapshotFlow` function of Compose to react of every month change, e.g 
```
val monthState = rememberSaveable(saver = MonthState.Saver()) {
    MonthState(initialMonth = YearMonth.now())
  }

  val calendarState = rememberCalendarState(
    monthState = monthState,
  )

  StaticCalendar(
    calendarState = calendarState,
  )
  
  LaunchedEffect(Unit) {
    snapshotFlow { monthState.currentMonth }
      .collect { currentMonth ->
        // viewModel.doSomething()
      }
  }
```
If you think that is not enough, feel free to write your suggestions.

**Comment by Foenix00001** [comment]
thank you, it is exactly what I wanted
