### ISSUE TITLE
Swiping to previous month issue

### ISSUE THREAD

**Issue by froz3nice** [boguszpawlowski/ComposeCalendar#87]
When user partially swipes towards previous month, calendar state immediately sets to previous month. Is there a way to set state only when user performs full swipe? (it works good while swiping to future months)

**Comment by froz3nice** [comment]
The version is 1.0.2

**Comment by boguszpawlowski** [comment]
Sorry for the late response. I'm able to reproduce on 1.0.2, will investigate further

**Comment by Schmoeffel** [comment]
Happens on 1.1.0 as well

**Comment by boguszpawlowski** [comment]
@Schmoeffel @froz3nice I found the problem, will release it in 1.1.1

**Comment by froz3nice** [comment]
your fix works, thanks!
