### ISSUE TITLE
Mode to start on Monday and finish on Sunday

### ISSUE THREAD

**Issue by JavierGonzal** [boguszpawlowski/ComposeCalendar#90]
Mode starts on Monday and finish on Sunday would be a nice feature to add.

Nice library btw, thanks :)

**Comment by boguszpawlowski** [comment]
Hi @JavierGonzal! You can specify first day of your week by passing it into the calendar object. See https://github.com/boguszpawlowski/ComposeCalendar#calendar-properties-customization and https://github.com/boguszpawlowski/ComposeCalendar/blob/main/sample/src/main/java/io/github/boguszpawlowski/composecalendar/sample/CustomComponentsSample.kt. Is this the feature you were looking for?
