### ISSUE TITLE
Support different languages

### ISSUE THREAD

**Issue by JavierGonzal** [boguszpawlowski/ComposeCalendar#93]
It's nice to have months and days in different languages like Spanish, French, and Portuguese.

**Comment by boguszpawlowski** [comment]
Hi @JavierGonzal. The language (I assume you mean default month and week headers), is based on the current Locale of the device, so it should follow the system settings. If you want more specific behavior, you can easily swap default headers implementation with your custom ones, as described here: https://github.com/boguszpawlowski/ComposeCalendar#calendar-with-custom-components
