### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by n7arti** [boguszpawlowski/ComposeCalendar#94]
I need help. I'm trying to figure out how the calendar works, but the code I paste from the examples doesn't work. Why?
Compose Version: 1.3.1
Compose Calendar Version: 1.1.0
![изображение_2023-03-14_142428549](https://user-images.githubusercontent.com/80055607/224986521-6229439b-e119-4e0c-9d3e-c1a6ce41c88a.png)
![image](https://user-images.githubusercontent.com/80055607/224986663-c90e779c-0a57-40a6-b122-ed3563f8a8fa.png)

**Comment by boguszpawlowski** [comment]
@n7arti Hi! As for the parameterName, there is an errorin Readme, it should be called `initialMonth` I will fix it shortly. As for the `plusYears` function, you are trying to invoke, you are using `YearMonth` from the kotlinx.datetime package. There is no `plusYears` function there, you have to either use `java.time` import, which I would suggest for your case, or use `plus(1,  DateTimeUnit.YEAR)` from `kotlinx.datetime` package
