### ISSUE TITLE
Issues with Gradle config for jetpack compose version 1.0.0-alpha11

### ISSUE THREAD

**Issue by NebilHassen** [boguszpawlowski/ComposeCalendar#98]
As the setup guide would suggest:

Jetpack Compose version: 1.0.0-alpha11, would have dependency version: 0.3.0 in both dependencies below. But this does not work. 
The only dependency combo that works is comisecalender:1.0.0 and and kotlinx-datetime:1.1.0, yet they still will not make ja regular datepicker show up in the emulator:

Should be an easy fix, anybody have the same experience?

As suggested on the setup guide: These do not work.
  dependecies {
    implementation "io.github.boguszpawlowski.composecalendar:composecalendar:0.3.0"
    
    implementation "io.github.boguszpawlowski.composecalendar:kotlinx-datetime:0.3.0"
  }

**Comment by boguszpawlowski** [comment]
Hi @NebilHassen Kotlinx-datetime was added in 0.5.0, so you wont be able to use 0.3.0 as it simply doesnt exist.
